---
# tasks file for mysql
- name: Install mysql
  apt: name={{ item }}
  with_items:
    - python-selinux
    - mysql-server
    - python-mysqldb

- name: Update root password
  mysql_user: name=root password={{mysql_pass}}

- name: Create /root/.my.cnf
  template:
    src: .my.cnf
    dest: /root/.my.cnf
    force: no

- name: Remove anonymous users
  mysql_user: name="" state=absent

- name: Remove test database
  mysql_db: name=test state=absent
