---

#- name: Update apt cache  #title show ra cho coi
#  command: apt update

- name: Install pip
  become: yes
#  apt: name=nginx state=present
  apt:
    name: python-pip
    state: present


- name: Install pydf
#  apt: name=nginx state=present
  pip:
    name: pydf
    state: present

